### PR TITLE
Fixed indentation (2 spaces per) and deleted trailing whitespace.

### PR DESCRIPTION
**Pull request by zenspider**
No other changes were made, as much as I wanted to. :)

### CODE REVIEW

**Comment by zenspider** [comment]
Another one incoming to quell warnings.
Then I'll probably take a stab at converting the tests.

**Comment by zenspider** [comment]
Oh... and there was one fix in there to get a test file loading... the file name had changed when the project name changed?

**Comment by zenspider** [comment]
tests all load now... but they're far from passing on my machine.

**Comment by zenspider** [comment]
testing is done, but I can't figure out how to do a PR that's clean until whitespace is merged in. 

warnings are next

**Comment by BrendanThompson** [comment]
@zenspider - The test stuff looks great. Is there a reason that you've removed whitespace etc out of the libs?

**Comment by zenspider** [comment]
For the most part to make it idiomatic ruby... but also because there was misindentation that was actually causing warnings. I just wrote an emacs macro to open every file, reindent everything, save, and move to the next file.

Are there any issues?

**Comment by zenspider** [comment]
Anything?

**Comment by zenspider** [comment]
Can you do a release please?

**Pull request merged**
