### PR TITLE
Fixed gemspec version

### PR DESCRIPTION
**Pull request by BrendanThompson**
Fixing the version number defined within the gemspec to align with whats been released

### CODE REVIEW

**Comment by zenspider** [comment]
Why are you requesting a review on a 1 char string change?

**Review by zenspider — APPROVED** [review]

**Comment by zenspider** [comment]
I always have my version number in a constant in the main class (so code can check against it or print it out in a usage output). Then my spec grabs the string from that. Still needs to be updated for every release, but it is more conspicuous since it is in the code that I am spending my time in.

**Comment by BrendanThompson** [comment]
@zenspider there is a requirement for reviews on all PRs into master, no matter how small :)

**Comment by zenspider** [comment]
While I want to help this project move forward, I am wholly uninterested in process for the sake of process. I've got too many projects to deal with that.

**Pull request merged**
